---
- name: Install prerequisites
  apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: yes

- name: Install K3s using official script
  become: yes
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version | default('v1.27.6+k3s1') }} sh -s - --write-kubeconfig-mode 644
  args:
    creates: /usr/local/bin/k3s

- name: Ensure kubeconfig present
  file:
    path: /etc/rancher/k3s/k3s.yaml
    state: file
