apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store-app
  labels:
    app.kubernetes.io/part-of: edgeops
spec:
  project: default
  source:
    repoURL: "https://github.com/your-org/edgeops-repo.git"
    targetRevision: HEAD
    path: deployments/store-app
  destination:
    server: https://kubernetes.default.svc
    namespace: store-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
